# CicleCI configuration file
version: 2.1
commands:
  send-to-git:
    parameters:
      when:
        type: string
    description: updated gitlab when fails
    steps:
      - run:
          command: git config --global user.email "circleCI@example.com"
      - run:
          command: git config --global user.name "Circle CI"
      - run:
          command: git add .
      - run:
          command: git commit -m "update from CircleCI"
      - run:
          command: git push origin main


orbs:
  node: circleci/node@5
jobs:
  build:
    # Build node project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  cypress-test:
    docker:
      - image: cypress/base:latest
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run cypress:ci
      - run:
          name: Run if test fail
          command: |
            git config user.email "circleCI@example.com" |
            git config user.name "Circle CI" |
            git checkout -b main && git checkout main
            git add . |
            rm -f .git/index.lock |
            git commit -m "update from CircleCI" |
            git push -q https://${Github_token}@github.com/bwilfong122/Cypress.git main
          when: on_fail
  # git:
  #   # Sends update to git
  #   executor: node/default
  #   steps:
  #     - run:
  #         command git config --global user.email "circleCI@example.com"
  #     - run:
  #         git config --global user.name "Circle CI"
  #     - run:
  #         command: git add .
  #     - run:
  #         command: git commit -m "update from CircleCI"
  #     - run:
  #         command: git push origin main
workflows:
  build-and-test:
    jobs:
      - build
      - cypress-test:
          requires:
            - build
      # - git:
      #     requires:
      #       - cypress-test
