# CicleCI configuration file
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    # Build node project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          command: publish "Update from circleCI"
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  cypress-test:
    docker:
      - image: cypress/base:latest
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run cypress:ci

workflows:
  build-and-test:
    jobs:
      - build
      - cypress-test:
          requires:
            - build
